<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>fp3_grasp_demo</name>
  <version>0.0.1</version>
  <description>v1: sends a hardcoded grasp pose to fp3_motion_server via the MoveToPose action</description>
  <maintainer email="n.elbachari@gmail.com">ngr</maintainer>
  <license>Apache-2.0</license>

  <depend>rclpy</depend>
  <depend>geometry_msgs</depend>
  <depend>franka_demo_interfaces</depend>

  <exec_depend>fp3_motion_server</exec_depend>
  <exec_depend>franka_fp3_moveit_config</exec_depend>

  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
