controller_names:
  - fp3_arm_controller
  - fp3_gripper

fp3_arm_controller:
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  default: true
  joints:
    - fp3_joint1
    - fp3_joint2
    - fp3_joint3
    - fp3_joint4
    - fp3_joint5
    - fp3_joint6
    - fp3_joint7

fp3_gripper:
    action_ns: gripper_action
    type: GripperCommand
    default: true
    joints:
      - fp3_finger_joint1
      - fp3_finger_joint2
