# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: google/robotics/developer/v1/modelserving.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
try:
  _runtime_version.ValidateProtobufRuntimeVersion(
      _runtime_version.Domain.PUBLIC,
      7,
      35,
      0,
      '',
      'google/robotics/developer/v1/modelserving.proto'
  )
except Exception:
  pass
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n/google/robotics/developer/v1/modelserving.proto\x12\x1cgoogle.robotics.developer.v1\"5\n\"RoboticsBidiGenerateContentRequest\x12\x0f\n\x07message\x18\x01 \x01(\x0c\"6\n#RoboticsBidiGenerateContentResponse\x12\x0f\n\x07message\x18\x01 \x01(\x0c\x32\xb7\x01\n\x0cModelServing\x12\xa6\x01\n\x1bRoboticsBidiGenerateContent\x12@.google.robotics.developer.v1.RoboticsBidiGenerateContentRequest\x1a\x41.google.robotics.developer.v1.RoboticsBidiGenerateContentResponse(\x01\x30\x01\x42$\n com.google.robotics.developer.v1P\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'google.robotics.developer.v1.modelserving_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n com.google.robotics.developer.v1P\001'
  _globals['_ROBOTICSBIDIGENERATECONTENTREQUEST']._serialized_start=81
  _globals['_ROBOTICSBIDIGENERATECONTENTREQUEST']._serialized_end=134
  _globals['_ROBOTICSBIDIGENERATECONTENTRESPONSE']._serialized_start=136
  _globals['_ROBOTICSBIDIGENERATECONTENTRESPONSE']._serialized_end=190
  _globals['_MODELSERVING']._serialized_start=193
  _globals['_MODELSERVING']._serialized_end=376
# @@protoc_insertion_point(module_scope)
